services:
  ackee:
    image: electerious/ackee
    container_name: ackee
    hostname: ackee
    networks:
     - traefik_network
    environment:
      - WAIT_HOSTS=ackee-mongo:27017
      - ACKEE_MONGODB=mongodb://ackee-mongo:27017/ackee
      - ACKEE_USERNAME=admin
      - ACKEE_PASSWORD=${ADMIN_PASSWORD}
      - ACKEE_TTL=3600000
      - ACKEE_ALLOW_ORIGIN=https://ackee.${DOMAINNAME}
    depends_on:
      - ackee-mongo
    restart: always  

  ackee-mongo:
    image: mongo
    container_name: ackee-mongo
    hostname: ackee-mongo
    networks:
     - traefik_network
    