networks:
  traefik_network:
    driver: bridge
    name: traefik_network
    external: true
services:
  gokapi:
    image: f0rc3/gokapi:latest
    environment:
    - TZ=${TZ}
    restart: unless-stopped
    container_name: gokapi
    hostname: gokapi
    networks:
    - traefik_network
    labels:
    - homepage.description=Expiring File Sharing
    - homepage.group=File Transfer
    - homepage.href=https://gokapi.${DOMAINNAME}/
    - homepage.icon=mdi-file
    - homepage.name=Gokapi
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=gokapi
    - traefik.enable=true
    - traefik.http.routers.gokapi.rule=Host(`gokapi.${DOMAINNAME}`)
    - traefik.http.services.gokapi.loadbalancer.server.port=53842
    volumes:
    - ${APPDATA_DIR}/gokapi/config:/app/config
    - ${APPDATA_DIR}/gokapi/data:/app/data
  aptabase:
    container_name: aptabase
    image: ghcr.io/aptabase/aptabase:main
    restart: always
    depends_on:
    - aptabase-clickhouse
    - aptabase-postgres
    volumes:
    - ${APPDATA_DIR}/aptabase/config/secrets:/lostack_secrets
    environment:
      BASE_URL: https://aptabase.${DOMAINNAME}:8000
      DATABASE_URL: Server=aptabase-postgres;Port=5432;User Id=aptabase;Password=${DATABASE_PASSWORD};Database=aptabase
      CLICKHOUSE_URL: Host=aptabase-clickhouse;Port=8123;Username=aptabase;Password=${DATABASE_PASSWORD}
      TZ: ${TZ}
    entrypoint: "sh -c '\n  if [ ! -f /lostack_secrets/auth.secret ]; then\n    echo\
      \ \"Generating new AUTH_SECRET...\"\n    mkdir -p /lostack_secrets\n    AUTH_SECRET=$(openssl\
      \ rand -hex 32)\n    echo \"AUTH_SECRET=$$AUTH_SECRET\" > /lostack_secrets/auth.secret\n\
      \  else\n    echo \"Using existing AUTH_SECRET from /lostack_secrets/auth.secret\"\
      \n  fi\n  . /lostack_secrets/auth.secret\n  export AUTH_SECRET\n  dotnet Aptabase.dll\n\
      '\n"
    hostname: aptabase
    networks:
    - traefik_network
    labels:
    - homepage.description=App Analytics
    - homepage.group=Analytics
    - homepage.href=https://aptabase.${DOMAINNAME}/
    - homepage.icon=aptabase
    - homepage.name=Aptabase
    - lostack.duration=15m
    - sablier.enable=true
    - sablier.group=aptabase
    - traefik.enable=true
    - traefik.http.routers.aptabase.rule=Host(`aptabase.${DOMAINNAME}`)
    - traefik.http.services.aptabase.loadbalancer.server.port=8080
  aptabase-postgres:
    container_name: aptabase-postgres
    image: postgres:15-alpine
    restart: always
    volumes:
    - ${APPDATA_DIR}/aptabase/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    hostname: aptabase-postgres
    networks:
    - traefik_network
    labels:
    - homepage.description=Aptabase Postgress
    - homepage.group=Databases
    - homepage.icon=postgres
    - homepage.name=Aptabase Postgres
    - sablier.enable=true
    - sablier.group=aptabase
  aptabase-clickhouse:
    container_name: aptabase-clickhouse
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    restart: always
    volumes:
    - ${APPDATA_DIR}/aptabase/events-db:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: aptabase-clickhouse
    networks:
    - traefik_network
    labels:
    - homepage.description=Aptabase Clickhouse
    - homepage.group=Databases
    - homepage.icon=clickhouse
    - homepage.name=Aptabase Clickhouse
    - sablier.enable=true
    - sablier.group=aptabase
  dufs:
    image: sigoden/dufs
    command: /data -A
    restart: unless-stopped
    container_name: dufs
    hostname: dufs
    networks:
    - traefik_network
    labels:
    - homepage.description=File Server Multitool
    - homepage.group=File Managers
    - homepage.href=https://dufs.${DOMAINNAME}/
    - homepage.icon=mdi-file-cabinet
    - homepage.name=Dufs
    - lostack.duration=1m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=dufs
    - traefik.enable=true
    - traefik.http.routers.dufs.rule=Host(`dufs.${DOMAINNAME}`)
    - traefik.http.services.dufs.loadbalancer.server.port=5000
    volumes:
    - ${APPDATA_DIR}/dufs:/data
  myip:
    container_name: myip
    image: jason5ng32/myip:latest
    restart: always
    hostname: myip
    networks:
    - traefik_network
    labels:
    - homepage.description=Web Security Tool
    - homepage.group=IP & Domain
    - homepage.href=https://myip.${DOMAINNAME}/
    - homepage.icon=mdi-incognito
    - homepage.name=Myip
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=myip
    - traefik.enable=true
    - traefik.http.routers.myip.rule=Host(`myip.${DOMAINNAME}`)
    - traefik.http.services.myip.loadbalancer.server.port=18966
  reubah:
    image: ghcr.io/dendianugerah/reubah:latest
    container_name: reubah
    hostname: reubah
    restart: unless-stopped
    networks:
    - traefik_network
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    labels:
    - traefik.enable=true
    - traefik.http.routers.reubah.rule=Host(`reubah.${DOMAINNAME}`)
    - traefik.http.services.reubah.loadbalancer.server.port=8081
    - homepage.name=Reubah
    - homepage.group=File Conversion
    - homepage.icon=mdi-autorenew
    - homepage.description=Bulk File Converter
    - homepage.href=https://reubah.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=reubah
    - lostack.duration=15m
    - lostack.primary=true
  tagspaces:
    image: tagspaces/tagspaces-lite-web:5.4.4
    restart: unless-stopped
    container_name: tagspaces
    hostname: tagspaces
    networks:
    - traefik_network
    labels:
    - homepage.description=File Organizer
    - homepage.group=File Managers
    - homepage.href=https://tagspaces.${DOMAINNAME}/
    - homepage.icon=mdi-tag-outline
    - homepage.name=Tagspaces
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=tagspaces
    - traefik.enable=true
    - traefik.http.routers.tagspaces.rule=Host(`tagspaces.${DOMAINNAME}`)
    - traefik.http.services.tagspaces.loadbalancer.server.port=80
  youtube-dl:
    image: nbr23/youtube-dl-server:latest
    restart: always
    container_name: youtube-dl
    hostname: youtube-dl
    networks:
    - traefik_network
    labels:
    - homepage.description=YouTube Downloader
    - homepage.group=Video Downloaders
    - homepage.href=https://youtube-dl.${DOMAINNAME}/
    - homepage.icon=youtube-dl
    - homepage.name=Youtube-dl
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=youtube-dl
    - traefik.enable=true
    - traefik.http.routers.youtube-dl.rule=Host(`youtube-dl.${DOMAINNAME}`)
    - traefik.http.services.youtube-dl.loadbalancer.server.port=8080
    volumes:
    - ${APPDATA_DIR}/youtube-dl:/youtube-dl
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    restart: always
    hostname: viseron
    networks:
    - traefik_network
    labels:
    - homepage.description=NVR with AI
    - homepage.group=Video Surveilance
    - homepage.href=https://viseron.${DOMAINNAME}/
    - homepage.icon=viseron
    - homepage.name=Viseron
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=viseron
    - traefik.enable=true
    - traefik.http.routers.viseron.rule=Host(`viseron.${DOMAINNAME}`)
    - traefik.http.services.viseron.loadbalancer.server.port=8888
    volumes:
    - ${MEDIA_DIR}/recordings:/recordings
    - ${APPDATA_DIR}/viseron:/config
    - /etc/localtime:/etc/localtime:ro
  h5ai:
    image: awesometic/h5ai
    container_name: h5ai
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=${TZ}
    restart: unless-stopped
    hostname: h5ai
    networks:
    - traefik_network
    labels:
    - homepage.description=HTTP Web Server
    - homepage.group=File Managers
    - homepage.href=https://h5ai.${DOMAINNAME}/
    - homepage.icon=mdi-file-cabinet
    - homepage.name=H5ai
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=h5ai
    - traefik.enable=true
    - traefik.http.routers.h5ai.rule=Host(`h5ai.${DOMAINNAME}`)
    - traefik.http.services.h5ai.loadbalancer.server.port=80
    volumes:
    - ${MEDIA_DIR}:/h5ai
    - ${APPDATA_DIR}/h5ai:/config
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - /dev/urandom:/dev/random:ro
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: ${DATABASE_PASSWORD}
      MB_DB_HOST: metabase-postgres
      TZ: ${TZ}
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
    - traefik_network
    labels:
    - homepage.description=Learn from Data
    - homepage.group=Analytics
    - homepage.href=https://metabase.${DOMAINNAME}/
    - homepage.icon=metabase
    - homepage.name=Metabase
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=metabase
    - traefik.enable=true
    - traefik.http.routers.metabase.rule=Host(`metabase.${DOMAINNAME}`)
    - traefik.http.services.metabase.loadbalancer.server.port=3000
  metabase-postgres:
    image: postgres:latest
    container_name: metabase-postgres
    hostname: metabase-postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    networks:
    - traefik_network
    labels:
    - homepage.description=Metabase Postgres
    - homepage.group=Databases
    - homepage.icon=postgres
    - homepage.name=Metabase Postgres
    - sablier.enable=true
    - sablier.group=metabase
  offen:
    image: offen/offen:v1.4.2
    environment:
      OFFEN_DATABASE_DIALECT: postgres
      OFFEN_DATABASE_CONNECTIONSTRING: postgres://user:${DATABASE_PASSWORD}@offen-postgres:5432/offen?sslmode=disable
      OFFEN_DATABASE_CONNECTIONRETRIES: 10
      TZ: ${TZ}
    volumes:
    - ${CERTS_DIR}/offen:/var/www/.cache
    depends_on:
    - offen-postgres
    container_name: offen
    hostname: offen
    networks:
    - traefik_network
    labels:
    - homepage.description=Web Analytics
    - homepage.group=Analytics
    - homepage.href=https://offen.${DOMAINNAME}/
    - homepage.icon=offen
    - homepage.name=Offen
    - lostack.duration=15m
    - lostack.primary=true
    - sablier.enable=true
    - sablier.group=offen
    - traefik.enable=true
    - traefik.http.routers.offen.rule=Host(`offen.${DOMAINNAME}`)
    - traefik.http.services.offen.loadbalancer.server.port=80
  offen-postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: offen
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    volumes:
    - ${APPDATA_DIR}/offen/db:/var/lib/postgresql/data
    container_name: offen-postgres
    hostname: offen-postgres
    networks:
    - traefik_network
    labels:
    - homepage.description=postgres service
    - homepage.group=Databases
    - homepage.icon=postgres
    - homepage.name=Offen Postgres
    - sablier.enable=true
    - sablier.group=offen
  pastefy:
    image: interaapps/pastefy:latest
    hostname: pastefy
    container_name: pastefy
    restart: unless-stopped
    networks:
    - traefik_network
    depends_on:
    - pastefy-db
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: '*'
      DATABASE_DRIVER: mysql
      DATABASE_NAME: pastefy
      DATABASE_USER: pastefy
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: pastefy-db
      DATABASE_PORT: 3306
      SERVER_NAME: https://pastefy.${DOMAINNAME}:80
    labels:
    - traefik.enable=true
    - traefik.http.routers.pastefy.rule=Host(`pastefy.${DOMAINNAME}`)
    - traefik.http.services.pastefy.loadbalancer.server.port=80
    - homepage.name=Pastefy
    - homepage.group=Pastebins
    - homepage.icon=mdi-clipboard-outline
    - homepage.description=Advanced Paste System
    - homepage.href=https://pastefy.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=pastefy
    - lostack.duration=15m
    - lostack.primary=true
  pastefy-db:
    image: mariadb:10.11
    hostname: pastefy-db
    container_name: pastefy-db
    networks:
    - traefik_network
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MYSQL_DATABASE: pastefy
      MYSQL_USER: pastefy
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
    - ${APPDATA_DIR}/pastefy:/var/lib/mysql
    labels:
    - homepage.name=Pastefy MariaBD
    - homepage.group=Databases
    - homepage.icon=mariadb
    - homepage.description=Pastefy DB
    - homepage.href=https://pastefy-db.${DOMAINNAME}/
    - sablier.enable=true
    - sablier.group=pastefy
