services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    depends_on:
      freshrss-db:
        condition: service_healthy
    networks:
      - traefik_network
    environment:
      TZ: ${TZ}
      CRON_MIN: '7,37'
      FRESHRSS_ENV: production
      COPY_LOG_TO_SYSLOG: 'On'
      COPY_SYSLOG_TO_STDERR: 'On'
      TRUSTED_PROXY: ${TRUSTED_PROXYS_CIDR}
      FRESHRSS_INSTALL: |
        --api_enabled
        --base_url https://freshrss.${DOMAINNAME}
        --db-base freshrss
        --db-host freshrss-db
        --db-password ${DATABASE_PASSWORD}
        --db-type pgsql
        --db-user freshrss
        --default_user admin
        --language en
      FRESHRSS_USER: |
        --api_password ${ADMIN_PASSWORD}
        --email admin@${DOMAINNAME} 
        --language en
        --password ${ADMIN_PASSWORD}
        --user admin
    logging:
      options:
        max-size: 10m

  freshrss-db:
    image: postgres:15-alpine
    container_name: freshrss-db
    restart: unless-stopped
    networks:
      - traefik_network
    environment:
      POSTGRES_DB: freshrss
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshrss"]
      interval: 10s
      timeout: 5s
      retries: 5