# - Bookmarks:
#     - Router:
#         href: https://192.168.1.1/
#         icon: netgear
#         description: "Home Router"

#     - Discord:
#         href: https://discord.com/channels/@me
#         icon: discord
#         description: "Discord Web App"