title: LoStack
theme: dark
favicon: /images/favicon.ico
background:
  image: /images/background_gradient.jpg
  saturate: 50
  brightness: 100
  opacity: 100
layout:
  Bookmarks:
    style: row
    columns: 4

  Admin:
    style: row
    columns: 4  

  Apps:
    style: row
    columns: 4

  Development:
    style: row
    columns: 4  

  File Conversion:
    style: row
    columns: 4  

  File Management:
    style: row
    columns: 4  

  Media:
    style: row
    columns: 4

  Tools:
    style: row
    columns: 4  

  Services:
    style: row
    columns: 4
    
  Background Services:
    style: row
    columns: 4

  Databases:
    style: row
    columns: 4

