services:
  lostack:
    container_name: lostack
    hostname: lostack
    networks:
      traefik_network: {}
    stop_signal: SIGINT
    depends_on:
      - lostack-db
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ}
      - DB_HOST=lostack-db
      - DB_PORT=3306
      - DB_USER=lostack
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=lostack-db
      - DOMAINNAME=${DOMAINNAME}
      - DOMAIN_NAME=${DOMAINNAME}
      - SABLIER_URL=http://sablier:10000
      - SABLIER_DEFAULT_SESSION_DURATION=15m
      - SABLIER_DEFAULT_THEME=ghost
      - TRUSTED_PROXY_IPS=${TRUSTED_PROXYS}

  lostack-db:
    image: mariadb:10.11
    container_name: lostack-db
    hostname: lostack-db
    networks:
      traefik_network: {}
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_DATABASE=lostack-db
      - MYSQL_USER=lostack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - TZ=${TZ}
