services:
  lostack:
    container_name: lostack
    hostname: lostack
    networks:
      traefik_network: {}
    stop_signal: SIGINT
    depends_on:
      - lostack-db
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ}

  lostack-ldap-test:
    container_name: lostack-ldap-test
    hostname: lostack-ldap-test
    networks:
      traefik_network: {}
    stop_signal: SIGINT
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ}    

  lostack-db:
    image: mariadb:10.11
    container_name: lostack-db
    hostname: lostack-db
    networks:
      traefik_network: {}
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_DATABASE=lostack-db
      - MYSQL_USER=lostack
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - TZ=${TZ}