
services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    hostname: arcane
    networks:
      - traefik_network
    environment:
      - APP_ENV=production
      - PUID=1000
      - PGID=1000
      - PUBLIC_SESSION_SECRET=${ARCANE_SESSION_SECRET}
    restart: unless-stopped