services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    hostname: excalidraw
    restart: unless-stopped
    networks:
      - traefik_network
    stdin_open: true
    healthcheck:
      disable: true