services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    networks:
      - traefik_network
    depends_on:
      miniflux-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:$DATABASE_PASSWORD@miniflux-db/miniflux-db?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - AUTH_PROXY_HEADER=Remote-User
      - AUTH_PROXY_USER_CREATION=1

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    networks:
      - traefik_network
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=miniflux-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s