services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    hostname: kavita
    networks:
      - traefik_network
    restart: unless-stopped
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}