

tls:
  options:
    modern:
      minVersion: VersionTLS13
    intermediate:
      minVersion: VersionTLS12
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  certificates:
    - certFile: '/certs/_wildcard.{{ env "DOMAINNAME" }}.pem'
      keyFile: '/certs/_wildcard.{{ env "DOMAINNAME" }}-key.pem'
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: '/certs/_wildcard.{{ env "DOMAINNAME" }}.pem'
        keyFile: '/certs/_wildcard.{{ env "DOMAINNAME" }}-key.pem'

http:
  # Enable to add local self-signed services
  # serversTransports:
  #   insecureTransport: 
  #     insecureSkipVerify: true

  middlewares:
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
          X-Forwarded-Proto: https
          server: ''
        customRequestHeaders:
          X-Forwarded-Proto: https
          X-Forwarded-Ssl: true
          X-Forwarded-Port: 443
          X-Forwarded-Host: '{{ env "DOMAINNAME" }}'
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: same-origin
        hostsProxyHeaders:
        - X-Forwarded-Host
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

    homepage-autostart:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          names: homepage
          sessionDuration: 30m
          dynamic:
            displayName: Homepage
            showDetails: false
            theme: ghost
            refreshFrequency: 3s
        
  services:
    homepage:
      loadBalancer:
        servers:
        - url: http://homepage:3000/

  routers:
    homepage-dynamic:
      rule: Host(`{{ env "DOMAINNAME" }}`)
      entryPoints:
      - https
      service: homepage
      middlewares:
      - homepage-autostart
