services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    hostname: jupyter
    restart: unless-stopped
    networks:
      - traefik_network
    command: start-notebook.sh
    user: root
    environment:
      NB_USER: ADMIN
      NB_UID: 1001
      NB_GID: 100
      CHOWN_HOME: 'yes'