services:
  authelia:
    image: authelia/authelia
    hostname: authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - traefik_network
    depends_on:
      - traefik
      - openldap
    environment:
      TZ: $TZ
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTHELIA_SERVER_BUFFERS_READ: 16384
      AUTHELIA_SERVER_BUFFERS_WRITE: 16384
      AUTHELIA_LOG_LEVEL: info
      AUTHELIA_LOG_FORMAT: text
      AUTHELIA_LOG_FILE_PATH: /config/authelia.log
      AUTHELIA_LOG_KEEP_STDOUT: false
      AUTHELIA_REGULATION_MAX_RETRIES: 10
      AUTHELIA_REGULATION_FIND_TIME: 2 minutes
      AUTHELIA_REGULATION_BAN_TIME: 3 minutes
      AUTHELIA_SERVER_ADDRESS: :${AUTHELIA_PORT}
      AUTHELIA_THEME: dark
      AUTHELIA_TOTP_ISSUER: authelia.com
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ATTRIBUTES_GROUP_NAME: cn
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION: custom
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: ldaps://openldap
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_START_TLS: false
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TLS_SKIP_VERIFY: true
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_TLS_MINIMUM_VERSION: TLS1.2
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: ${LDAP_BASE_DN}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: ou=people
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER: (&({username_attribute}={input})(objectClass=person))
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: ou=groups
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER: (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: cn=${LDAP_ADMIN_USER},${LDAP_BASE_DN}
      DOMAINNAME: ${DOMAINNAME}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      CUST_AUTHELIA_PREFIX: ${AUTHELIA_PREFIX}
      CUST_AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      CUST_AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      CUST_AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}