# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM python:3.10-alpine AS builder

WORKDIR /sablier-gui

RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    make

COPY requirements.txt /sablier-gui

# Install Python Docker dependencies
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install docker

# Install Python requirements
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /sablier-gui

ENTRYPOINT ["python3", "-u", "app.py"]

# Dev environment stage
FROM builder AS dev-envs

# Add user
RUN addgroup -S docker && \
    adduser -S --shell /bin/bash --ingroup docker 